JohnSundell/Files

Sources/Files.swift

I'm trying to _dockerize_ some scripts and I had troubles compiling this on Linux. Here's the error message:
```
Compile Swift Module 'Files' (1 sources)
/Users/garriguv/github.com/garriguv/Files/Sources/Files.swift:661:12: error: value of type 'ObjCBool' (aka 'Bool') has no member 'boolValue'
if objCBool.boolValue {
^~~~~~~~ ~~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): /usr/bin/swift-build-tool -f /Users/garriguv/github.com/garriguv/Files/.build/debug.yaml
```
This change allows the library to compile on Linux 🐧

Use Bool initializer instead of boolValue

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

Fixed https://github.com/JohnSundell/Marathon/issues/21
The error I fixed is like this,
```
Test Case '-[Files_iOS_Tests.FilesTests testCreatingFileFromFileSystem]' started.
/Users/pixyzehn/Developer/projects/Files/Tests/FilesTests/FilesTests.swift:446: error: -[Files_iOS_Tests.FilesTests testCreatingFileFromFileSystem] : XCTAssertEqual failed: ("/Users/pixyzehn/Library/Developer/CoreSimulator/Devices/CBC21E18-DBF9-40C5-B3C7-A17E671E1292/data/tmp/one/two//three") is not equal to ("/Users/pixyzehn/Library/Developer/CoreSimulator/Devices/CBC21E18-DBF9-40C5-B3C7-A17E671E1292/data/tmp/one/two/three") - 
```

Fix create file at path method

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

Add the possibility to reach the current folder with:
```swift
import Files
var current = Folder.current
```
This is an alternative to `FileSystem().currentFolder`.
We could imagine add the same for the home folder, temporary folder and so on.

Add syntactic sugar to reach the current folder.

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

This is just a _convencience_ wrapper as there's already one for folders called `createFolderIfNeeded`. Of course, you can use the one in `Folder`, but it's way more convenience to have consistent API (or maybe I missed something?).

Method for creating file if needed from FileSystem

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

This change introduces a new property on `FileSystem.Item`; `modifiedDate`, which contains the date that the item was last modified on. Works for both `Files` and `Folders`.

FileSystem.Item: Add modifiedDate property

---

Tests/FilesTests/FilesTests.swift

- Test folder is now only created when needed, and emptied.
- Testing creating folder with tilde now uses unique folder name.

Fix test failures with folder name collisions

---

Sources/Files.swift

Now uses a substring rather than string replacement

FileSystemItem: Simplify nameExcludingExtension calculation

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

I added an `includeHidden` parameter to `Folder.moveContents()` (that defaults to `false` so that the default behavior is unaffected) to allow for hidden files and folders to be moved. Came across the need for this functionality in a script I was writing where `.git` and `.gitignore` were not moved when using `moveContents()`.

Move hidden folder contents

---

Package.swift

To tell SPM to use Swift 4 to compile the project.

Use Swift 4 version of the Package Description API

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

Fix 45 - Moving a folder using move(to:) creates an invalid path

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

Making `FileSystemSequence` `CustomStringConvertible` provides a better description, which is really helpful especially for debugging. For printing  a `folder`'s `subfolders` instead of:
```
<FileSystemSequence<Folder>: 0x102553ed0>
```
we will get:
```
Folder(name: folderA, path: path_to_folder/folderA/)
Folder(name: folderB, path: path_to_folder/folderB/)
```

Makes `FileSystemSequence` `CustomStringConvertible`

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

Add appending data/string to files like `bash`'s `>>` operator.
```swift
func append(data: Data) throws
func append(string: String, encoding: String.Encoding = .utf8) throws
```
This should close #48.

Add append to file

---

.travis.yml
Sources/Files.swift

Hey John 👋 
The latest release broke `Files` for consumers & libraries that need Swift 4.0 support on Linux.
This PR:  
* Fixes #54 - Swift 4.0 support for Linux 
* Updates travis to run all combinations of Swift 4.0 / 4.1 - Linux & MacOS. Screenshot below.

Add support for Swift 4.0 & update CI

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

This PR adds two methods to `Folder`:
1. `contains(_ file: File)`
2. `contains(_ subfolder: Folder)`
Resolves #60

Folder contains file/subfolder

---

Sources/Files.swift

Has been deprecated since version 1.4.0, so time to remove it.

Remove deprecated ‘creatingSubfolderFailed’ API

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

Apps on iOS-based operating systems don’t have access to these kinds of system resources.

Only enable accessing Documents and Library folders on macOS

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

This enables an easy way to work with relative paths, for example when dealing with multiple files that are within the same folder structure.

Add API for computing a path relative to a parent folder

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

This change introduces an API to directly convert a sequence of files into a recursive one, rather than having to use `Folder`’s `makeFileSequence(recursive: true)` method.

FileSystemSequence: Add API for converting to recursive

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

This patch fixes a regression that would cause a copied file or folder not to be returned as part of that operation. A test has also been added to make sure that this feature stays intact in the future.

Return copied filed/folder when calling copy()

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

This patch fixes a bug that would cause a new file’s content to not be considered when using the `createFileIfNeeded` API.
Thanks to @maximkrouk for reporting this issue.

Fix content not being considered when creating file if needed

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

Currently using `nameExcludingExtension` on a location that doesn’t actually have an extension results in an empty string, which this patch fixes. Now the full name is returned instead in those situations.

Fix nameExcludingExtension bug when there’s no extension

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

This change adds a public API for resolving a folder for a given search path within a domain. This new API is now also used internally to resolve the current user’s “Documents” and “Library” folders.

Folder: Add API for resolving search paths

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

Hello John and thanks for this great library! 👋 
I've recently started to use this package with the new [Swift Argument Parser](https://github.com/apple/swift-argument-parser) and it works flawlessly.
The thing is that is that every time wrong arguments are passed and error is thrown in Files, it is printed out with a typo like this:
```
Error: Files encounted an error at '/some/path'.
Reason: missing
Program ended with exit code: 1
```
*TLDR: I fixed a typo in the error which you are getting a lot during development/using the library.*

Fix typo in files error description

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

This change makes the built-in APIs for retrieving the system-provided `Documents` and `Library` folders available on iOS and tvOS, as well as macOS (which was already supported).

Extend build-in support for Documents and Library folders to more platforms

---

Sources/Files.swift
Tests/FilesTests/FilesTests.swift

This change adds a possibility to check if a folder is empty, including hidden files.

Add `isEmpty` method for `Folder`
